#pragma once

enum PAGRevObjParts : int 
{ 
	PAG_BODY = 0,
	PAG_TOP_FAN = 1,
	PAG_BOTTOM_FAN = 2 
};

enum PAGProfileParts : int
{
	PAG_PROF_BODY = 0,
	PAG_TOP_LID = 1,
	PAG_BOTTOM_LID = 2
};

enum PAGDrawingMode : int
{
	PAG_POINT_VIEW ,
	PAG_LINE_VIEW ,
	PAG_TRIANGLE_VIEW ,
	PAG_POINT_LINE_TRIANGLE_VIEW ,
	PAG_FRONT_FACE_VIEW ,
	PAG_NORMALS_AS_COLORS_VIEW,
	PAG_TANGENTS_AS_COLORS_VIEW,
	PAG_TEXTURE_COORDS_AS_COLORS_VIEW,
	PAG_MAGIC_VIEW
};

enum PAGShader : int
{
	PAG_POINT_SHADER,
	PAG_LINE_SHADER ,
	PAG_TRIANGLE_SHADER ,
	PAG_NORMALS_AS_COLORS_SHADER,
	PAG_FRONT_FACE_SHADER,
	PAG_TANGENTS_AS_COLORS_SHADER,
	PAG_TEXTURE_COORDS_AS_COLORS_SHADER,
	PAG_MAGIC_SHADER,
	PAG_SPOTLIGHT_SHADER ,
	PAG_DIRLIGHT_SHADER,
	PAG_POINTLIGHT_SHADER ,
	PAG_AMBIENTLIGHT_SHADER,
	PAG_FOG_SHADER
};