#pragma once

enum PAGRevObjParts : int 
{ 
	PAG_BODY = 0,
	PAG_TOP_FAN = 1,
	PAG_BOTTOM_FAN = 2 
};

enum PAGProfileParts : int
{
	PAG_PROF_BODY = 0,
	PAG_TOP_LID = 1,
	PAG_BOTTOM_LID = 2
};

enum PAGDrawingMode : int
{
	PAG_POINT_VIEW = 0,
	PAG_LINE_VIEW = 1,
	PAG_TRIANGLE_VIEW = 2,
	PAG_POINT_LINE_TRIANGLE_VIEW = 3,
	PAG_FRONT_FACE_VIEW = 4,
	PAG_NORMALS_AS_COLORS_VIEW = 5,
	PAG_TANGENTS_AS_COLORS_VIEW = 6,
	PAG_TEXTURE_COORDS_AS_COLORS_VIEW = 7,
	PAG_MAGIC_VIEW = 8
};